name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # This triggers the workflow on push to the `master` branch
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out your repository code

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3  # Sets up the .NET SDK
      with:
        dotnet-version: '9.0'  # Specify the version of .NET you are using

    - name: Restore dependencies
      run: |
        cd DNTkalenderinator
        dotnet restore DNTkalenderinator.csproj  # Restore the dependencies for your project

    - name: Publish the .NET app
      run: |
        cd DNTkalenderinator
        dotnet publish -c Release -o ./publish  # Publish the .NET app to the `./publish` folder

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for multi-platform builds

    - name: Build Docker image
      run: |
        cd DNTkalenderinator
        docker build -t markusklingerdolvik/dntkalenderinator:latest .  # Use the DNTkalenderinator folder as the Docker context

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Logs into Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets for Docker Hub password

    - name: Push Docker image to Docker Hub
      run: |
        docker push markusklingerdolvik/dntkalenderinator:latest  # Push the image to Docker Hub